### ISSUE TITLE
Deadlock on PyPy when optimize?

### ISSUE THREAD

**Issue by x64s** [backtrader/backtrader#350]
I've tested some strategies with CPython. All worked well except execution time.
PyPy works 16 times faster, but...
But it fails after 5 or 10 or 30 minutes of work.
Error seems like a deadlock - there is no error in console, but testing paused.

When I press Ctrl+C I see this error in stacktrace:
KeyboardInterrupt
Traceback (most recent call last):
  File "../lib-python/3/multiprocessing/pool.py", line 680, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

 File ".../site-packages/backtrader/cerebro.py", line 1140, in run
    for r in pool.imap(self, iterstrats):
  File ".../lib-python/3/multiprocessing/pool.py", line 684, in next
    self._cond.wait(timeout)
  File ".../lib-python/3/threading.py", line 293, in wait
    waiter.acquire()

**Comment by mementum** [comment]
All those *Exceptions* happen outside of `backtrader` which uses a single call to kick-start the multi-core processing of the strategies: `pool.imap`

If it works in *CPython* it is a bug in *pypy* (it may also be a bug in *Cpython* which is only uncovered when executing under *pypy* due to subtle differences in the implementation which trigger the right conditions for the bug.

**Comment by x64s** [comment]
Seems that it was fixed by changing 
pool.imap(..):  -> pool.map(..)

Works fast and stable now.

**Comment by x64s** [comment]
@mementum could you please explain advantages of using .imap() in this place
or maybe risks of .map()
?

**Comment by mementum** [comment]
From `README.rst`

**Tickets**

  If it's **NOT an issue** (i.e.: bug), don't post it as an issue. It will be
  automatically closed.

For **feedback/questions/...** use the `Community <https://community.backtrader.com>`_
