### ISSUE TITLE
AttributeError: 'str' object has no attribute '_name'

### ISSUE THREAD

**Issue by gengstah** [backtrader/backtrader#357]
Hello,

I am encountering an AttributeError on broker.py. Please see stacktrace below:

```python
Starting Portfolio Value: 20000.00
Traceback (most recent call last):
  File "test3_multiple_data_feeds.py", line 206, in <module>
    results = cerebro.run()
  File "..\backtrader\cerebro.py", line 1127, in run
    runstrat = self.runstrategies(iterstrat)
  File "..\backtrader\cerebro.py", line 1290, in runstrategies
    self._runonce(runstrats)
  File "..\backtrader\cerebro.py", line 1684, in _runonce
    self._brokernotify()
  File "..\backtrader\cerebro.py", line 1357, in _brokernotify
    self._broker.next()
  File "..\backtrader\brokers\bbroker.py", line 1230, in next
    self._get_value()  # update value
  File "..\backtrader\brokers\bbroker.py", line 440, in _get_value
    comminfo = self.getcommissioninfo(data)
  File "..\backtrader\broker.py", line 80, in getcommissioninfo
    if data._name in self.comminfo:
AttributeError: 'str' object has no attribute '_name'
```

This is the `next` method on my strategy which I assumed is causing this error:

```python
def next(self):
        for d in self.getdatanames():
            dt = self.datetime.datetime()
            pos = self.getposition(d).size or 0
            print('{} Position {} {}'.format(dt, d, pos))
            
            if pos == 0:
                if self.buysig[d] > 0:
                    print('{} Buy {}'.format(dt, d))
                    self.buy(data=self.getdatabyname(d))
            else:
                if self.sellsig[d] > 0:
                    print('{} Sell {} {}'.format(dt, d, pos))
                    self.sell(data=self.getdatabyname(d))
```

Am I doing something wrong?

**Comment by gengstah** [comment]
I got it working by modifying the `next` method. Here is the code now:

```python
def next(self):
        for i, d in enumerate(self.datas):
            dt = self.datetime.datetime()
            pos = self.getposition(d).size or 0
            print('{} Position {} {}'.format(dt, d._name, pos))
            
            if pos == 0:
                if self.buysig[d] > 0:
                    print('{} Buy {}'.format(dt, d._name))
                    self.buy(data=d)
            else:
                if self.sellsig[d] > 0:
                    print('{} Sell {} {}'.format(dt, d._name, pos))
                    self.sell(data=d)
```
